# id of the links that are digits
digit_link_id_arg85: [13, 19]

pybullet_camera:
  cameraDistance: 0.4
  cameraYaw: 45.
  cameraPitch: -45.
  cameraTargetPosition: [0, 0, 0]

tacto:
  width: 120
  height: 160
  visualize_gui: True

object_control_panel:
  slider_params:
    position_low: [-0.3, -0.3, 0]
    position_high: [0.3, 0.3, 0.3]

# Neccesary parameters of the target object;
# The global scaling is used to shrink the size of the object
target_object:
  object_name: Mug
  object_position: [0, 0, 0]
  global_scaling : 0.5

simulation:
  camera_pos : [0.5, 1, 0.7]
  camera_pos_2 : [1.5, -1, 0.7]

  pitch : -20.0
  yaw : 0
  roll : 0
  fov : 30 


